dbctl on the go

diff --git a/resources/dbctl/dbctl b/resources/dbctl/dbctl
--- a/resources/dbctl/dbctl
+++ b/resources/dbctl/dbctl
@@ -25,31 +25,61 @@ eval_command(){
   eval "$EVAL_COMMAND"
 }
 
+# @description return the dump format from a path
+# @stdout the dump format
+# @exitcode 1 if not format could be determined
+get_dump_format_from_path(){
+
+  DUMP_PATH=$1
+  EXTENSION=$(path::get_extension "$DUMP_PATH")
+  case $EXTENSION in
+    "$DUMP_CUSTOM_FILE_EXTENSION")
+      echo $DUMP_CUSTOM_FORMAT
+      return
+      ;;
+    "$DUMP_PLAIN_FILE_EXTENSION"|"$DUMP_PLAIN_FILE_EXTENSION.gz")
+      echo $DUMP_PLAIN_FORMAT
+      ;;
+    *)
+      echo::err "The dump file ($DUMP_PATH) is not an archive (.$DUMP_CUSTOM_FILE_EXTENSION), nor a sql dump (.$DUMP_PLAIN_FILE_EXTENSION, .sql.gz)"
+      return 1
+  esac
+
+}
 
 # @description return the dump file path
 # @arg $1 - the dump format
 # @arg $2 - the database name
-get_db_dump_file(){
+get_db_dump_path(){
   
   local DUMP_FORMAT=$1
   local DATABASE_NAME=$2
 
   # All dump files start with this prefix path
-  local DB_DUMP_PATH_PREFIX="$DUMP_SNAPSHOT_DIR/dumpfile-db"
   local FILE_EXTENSION;
+  # The prefix for a file
+  local DUMP_FILE_PREFIX="dump-file"
   case $DUMP_FORMAT in
     "$DUMP_PLAIN_FORMAT")
-      FILE_EXTENSION=$DUMP_PLAIN_FILE_EXTENSION
+      FILE_EXTENSION=".$DUMP_PLAIN_FILE_EXTENSION"
+      DUMP_PATH_PREFIX=$DUMP_FILE_PREFIX
       ;;
     "$DUMP_CUSTOM_FORMAT")
-      FILE_EXTENSION=$DUMP_CUSTOM_FILE_EXTENSION
+      FILE_EXTENSION=".$DUMP_CUSTOM_FILE_EXTENSION"
+      DUMP_PATH_PREFIX=$DUMP_FILE_PREFIX
       ;;
+    "$DUMP_FORMAT_DIR")
+      FILE_EXTENSION=""
+      DUMP_PATH_PREFIX="dump-dir"
+      echo "$DB_DUMP_PATH_PREFIX-${DATABASE_NAME}"
+    ;;
     *)
       echo::err "File extension $DUMP_FORMAT does not produce a file"
       return 1
   esac
-  
-  echo "$DB_DUMP_PATH_PREFIX-${DATABASE_NAME}.$FILE_EXTENSION"
+
+  echo "$DUMP_SNAPSHOT_DIR/$DUMP_PATH_PREFIX-db-${DATABASE_NAME}$FILE_EXTENSION"
+
   
 }
 
@@ -69,32 +99,32 @@ cleaning_snapshot_dir(){
 # @exitcode 2 if the file does not exist or is empty
 validate_postgres_dump() {
 
-    local DUMP_FILE="$1"
+    local DUMP_PATH="$1"
 
     # Check if file exists
-    if [[ ! -f "$DUMP_FILE" ]]; then
-        echo::err "Error: File $DUMP_FILE does not exist."
+    if [[ ! -f "$DUMP_PATH" ]]; then
+        echo::err "Error: File $DUMP_PATH does not exist."
         return 2
     fi
 
     # Check if file is empty
-    if [[ ! -s "$DUMP_FILE" ]]; then
+    if [[ ! -s "$DUMP_PATH" ]]; then
         echo::err "Error: File is empty."
         return 2
     fi
 
-    DUMP_FILE_EXTENSION=$(path::get_extension $DUMP_FILE)
+    DUMP_FILE_EXTENSION=$(path::get_extension $DUMP_PATH)
     case $DUMP_FILE_EXTENSION in
         "$DUMP_CUSTOM_FILE_EXTENSION")
           # The -l, --list option print summarized TOC of the custom archive format
-          VALIDITY_COMMAND="pg_restore -l $DUMP_FILE &>/dev/null"
+          VALIDITY_COMMAND="pg_restore -l $DUMP_PATH &>/dev/null"
           echo::info "Checking the $DUMP_FILE_EXTENSION dump with the command: $VALIDITY_COMMAND"
           if ! eval "$VALIDITY_COMMAND"; then
               echo::err "pg_restore cannot read the file structure. The dump may be corrupted."
               return 1
           fi
           echo::info "pg_restore can read the file structure."
-          TABLE_COUNT_COMMAND="pg_restore -l $DUMP_FILE | grep -c 'TABLE'"
+          TABLE_COUNT_COMMAND="pg_restore -l $DUMP_PATH | grep -c 'TABLE'"
           echo::info "Getting the table count with the command: $TABLE_COUNT_COMMAND"
           # Without any table, the grep fail
           if ! TABLE_COUNT=$(eval "$TABLE_COUNT_COMMAND"); then
@@ -105,20 +135,20 @@ validate_postgres_dump() {
           fi
         ;;
         "$DUMP_PLAIN_FILE_EXTENSION")
-          VALIDITY_COMMAND="grep -q 'PostgresSQL database dump complete' $DUMP_FILE"
+          VALIDITY_COMMAND="grep -q 'PostgresSQL database dump complete' $DUMP_PATH"
           echo::info "Checking the $DUMP_FILE_EXTENSION dump with the command: $VALIDITY_COMMAND"
           if ! eval "$VALIDITY_COMMAND"; then
               echo::err "pg_restore cannot read the file structure. The dump may be corrupted."
               return 1
           fi
           echo::info "pg_restore can read the file structure."
-          TABLE_COUNT_COMMAND="grep -c 'CREATE TABLE' $DUMP_FILE"
+          TABLE_COUNT_COMMAND="grep -c 'CREATE TABLE' $DUMP_PATH"
           echo::info "Getting the table count with the command: $TABLE_COUNT_COMMAND"
           TABLE_COUNT=$(eval "$TABLE_COUNT_COMMAND");
           echo::info "Info: Dump contains approximately $TABLE_COUNT tables."
         ;;
         *)
-          echo::err "The extension (${DUMP_FILE_EXTENSION}) is unknown (File $DUMP_FILE)"
+          echo::err "The extension (${DUMP_FILE_EXTENSION}) is unknown (File $DUMP_PATH)"
           return 1
     esac
 
@@ -159,14 +189,13 @@ function backup_restore_help() {
   echo ""
   echo "The 'backup restore' command restores a database from a dump"
   echo ""
-  echo "   ${CLI_NAME} backup restore [--db targetDbName] [--path dumpPath] [--id snapshotId]"
+  echo "   ${CLI_NAME} backup restore [--db targetDbName] [--path dumpPath] (snapshotId|locaPath)"
   echo ""
   echo "where:"
-  echo "  * --id   snapshotId   - the id of a snapshot backup or latest"
+  echo "  * args: mandatory, one of:"
+  echo "      * snapshotId        - the id of a snapshot backup or latest"
   echo "                            * You can get them with the command 'backup ls'"
-  echo "  * --path dumpPath     - the path to the dump file"
-  echo "                            * in a snapshot (if a snapshotId specified)"
-  echo "                            * otherwise on the local file system"
+  echo "      * localPath         - a local path to a dump file"
   echo "  * --db   targetDbName - the database target for the restoration"
   echo "                            * by default: ${CTL_DATABASE_NAME}"
   echo ""
@@ -174,11 +203,11 @@ function backup_restore_help() {
   echo ""
   echo "  * Restore the latest snapshot in the default database (${CTL_DATABASE_NAME})"
   echo ""
-  echo "     ${CLI_NAME} backup restore --id latest"
+  echo "     ${CLI_NAME} backup restore latest"
   echo ""
   echo "  * Restore a local dump file in a new database called tempdb"
   echo ""
-  echo "     ${CLI_NAME} backup restore --db tempdb --path /data/pgdump/dumpfile-db-postgres.dump"
+  echo "     ${CLI_NAME} backup restore --db tempdb /data/pgdump/dumpfile-db-postgres.dump"
   echo ""
 
 
@@ -283,19 +312,10 @@ function backup_restore_command(){
 
   echo::info "Backup restore initialized"
 
-  if [ -z "${ARGS[0]}" ]; then
-      backup_restore_help
-      echo::err 'A Snapshot Id or a absolute path should be given as argument'
-      echo::err ""
-      echo::err 'Tip:'
-      echo::err "  * You can get a snapshot id with the command 'backup ls' command"
-      echo::err "  * You can use 'latest' if you want to use the latest snapshot"
-      exit 1
-  fi
 
-  SNAPSHOT_ID=""
-  DUMP_PATH=""
-  TARGET_DB_NAME=$CTL_DATABASE_NAME
+  local SNAPSHOT_ID=""
+  local DUMP_PATH=""
+  local TARGET_DB_NAME=$CTL_DATABASE_NAME
   while [[ $# -gt 0 ]]; do
     case "$1" in
       -d|--db)
@@ -309,10 +329,11 @@ function backup_restore_command(){
         shift
         ;;
       *)
-        if [[ "$1" == /* ]]; then
-          DUMP_PATH=$1
-        else
+        EXTENSION=$(path::get_extension "$1")
+        if [[ "$EXTENSION" == "" ]]; then
           SNAPSHOT_ID=$1
+        else
+          DUMP_PATH=$1
         fi
         shift
         ;;
@@ -334,49 +355,46 @@ function backup_restore_command(){
     eval_command "restic restore --include ${INCLUDE_PATH_PATTERN} --target $RESTORE_DIR --verify ${SNAPSHOT_ID}"
     echo::info "Fetching done"
 
-    if [ "$DUMP_PATH" == "" ]; then
-      echo::info "Searching a valid dump file in the snapshot ${SNAPSHOT_ID}"
-      DUMP_FILE=$(get_db_dump_file $DUMP_CUSTOM_FORMAT $TARGET_DB_NAME)
-      CUSTOM_DUMP_FILE_TO_RESTORE="${RESTORE_DIR}${DUMP_FILE}"
-      if [ -f  "$CUSTOM_DUMP_FILE_TO_RESTORE" ]; then
-          DUMP_FILE_TO_RESTORE=$CUSTOM_DUMP_FILE_TO_RESTORE
-          DUMP_FORMAT=$DUMP_FORMAT_TAR
-      else
-        DUMP_FILE=$(get_db_dump_file $DUMP_DUMP_PLAIN_FORMAT $TARGET_DB_NAME)
-        SQL_DUMP_FILE_TO_RESTORE="${RESTORE_DIR}/${DUMP_FILE}"
-        if [ ! -f  "$SQL_DUMP_FILE_TO_RESTORE" ]; then
-          echo::err "We could not find any dump file to restore in the SNAPSHOT_ID ${SNAPSHOT_ID}"
-          echo::err "  * No SQL dump found at $SQL_DUMP_FILE_TO_RESTORE"
-          echo::err "  * No Archive dump found at ${CUSTOM_DUMP_FILE_TO_RESTORE}"
-          echo::err ""
-          echo::err "You can give one with the  '--path' parameter"
-          exit 1
-        fi
-        DUMP_FILE_TO_RESTORE=$SQL_DUMP_FILE_TO_RESTORE
-        DUMP_FORMAT=$DUMP_PLAIN_FORMAT
-      fi
-      echo::info "Dump file $DUMP_FILE_TO_RESTORE found"
+    echo::info "Searching a valid dump file in the snapshot ${SNAPSHOT_ID}"
+    DUMP_PATH=$(get_db_dump_path "$DUMP_CUSTOM_FORMAT" "$TARGET_DB_NAME")
+    CUSTOM_DUMP_FILE_TO_RESTORE="${RESTORE_DIR}${DUMP_PATH}"
+    if [ -f  "$CUSTOM_DUMP_FILE_TO_RESTORE" ]; then
+        DUMP_FILE_TO_RESTORE=$CUSTOM_DUMP_FILE_TO_RESTORE
     else
-      DUMP_FILE_TO_RESTORE="${RESTORE_DIR}/${DUMP_PATH}"
-      if [ ! -f  "$DUMP_FILE_TO_RESTORE" ]; then
-          echo::err "The SNAPSHOT_ID ${SNAPSHOT_ID} does not contains the ${DUMP_PATH}"
-          echo::err "  * No file found at $DUMP_FILE_TO_RESTORE"
-          exit 1
+      DUMP_PATH=$(get_db_dump_path "$DUMP_PLAIN_FORMAT" "$TARGET_DB_NAME")
+      SQL_DUMP_FILE_TO_RESTORE="${RESTORE_DIR}/${DUMP_PATH}"
+      if [ ! -f  "$SQL_DUMP_FILE_TO_RESTORE" ]; then
+        echo::err "We could not find any dump file to restore in the snapshot ${SNAPSHOT_ID}"
+        echo::err "  * No SQL dump found at ${SQL_DUMP_FILE_TO_RESTORE}"
+        echo::err "  * No Custom dump found at ${CUSTOM_DUMP_FILE_TO_RESTORE}"
+        echo::err ""
+        echo::err "You can give one by passing one of the local path of the snapshot ${SNAPSHOT_ID}.\n$(find "${RESTORE_DIR}")"
+        echo::err ""
+        echo::err "Choose one and execute:"
+        echo::err ""
+        echo::err "  $CLI_NAME backup restore locaPath"
+        exit 1
       fi
-      if echo "$DUMP_PATH" | grep -q '\.dump$';  then
-        DUMP_FORMAT=$DUMP_FORMAT_TAR
-      else
-        if ! echo "$DUMP_PATH" | grep -q '\.sql.gz$';  then
-          echo::err "The dump file ($DUMP_PATH) is not an archive (.dump), nor a sql dump (.sql.gz)"
-          exit 1
-        fi
-        DUMP_FORMAT=$DUMP_PLAIN_FORMAT
-      fi
+      DUMP_FILE_TO_RESTORE=$SQL_DUMP_FILE_TO_RESTORE
     fi
+    echo::info "Dump file $DUMP_FILE_TO_RESTORE found"
+
   else
+    if [ "$DUMP_PATH" == "" ]; then
+        backup_restore_help
+        echo::err 'A Snapshot Id or a local path should be given as argument'
+        echo::err ""
+        echo::err 'Tip:'
+        echo::err "  * You can get a snapshot id with the command 'backup ls' command"
+        echo::err "  * You can use 'latest' if you want to use the latest snapshot"
+        exit 1
+    fi
     # Local dump path file to restore
     DUMP_FILE_TO_RESTORE=$DUMP_PATH
   fi
+
+  # Format
+  DUMP_FORMAT=$(get_dump_format_from_path "$DUMP_FILE_TO_RESTORE")
 
   echo::info "Validating the dump file"
   validate_postgres_dump "${DUMP_FILE_TO_RESTORE}"
@@ -405,19 +423,18 @@ function backup_restore_command(){
   echo::info "Database created"
 
   echo::info "Restoring the database with a $DUMP_FORMAT format"
-  if [ "$DUMP_FORMAT" == "$DUMP_PLAIN_FORMAT" ]; then
-
-
-    echo::info "Loading the dump"
-    eval_command "gunzip < ${DUMP_FILE_TO_RESTORE} | psql --set ON_ERROR_STOP=on --single-transaction ${TARGET_DB_NAME}";
-
-  else
-
-    # the -d option makes a direct connection with libpq
-    # If the connection does not work, try with psql
-    eval_command "pg_restore --clean -d ${TARGET_DB_NAME} ${DUMP_FILE_TO_RESTORE}"
-
-  fi
+  case "$DUMP_FORMAT" in
+    "$DUMP_PLAIN_FORMAT")
+      eval_command "gunzip < ${DUMP_FILE_TO_RESTORE} | psql --set ON_ERROR_STOP=on --single-transaction ${TARGET_DB_NAME}";
+      ;;
+    "$DUMP_CUSTOM_FORMAT")
+      # the -d option makes a direct connection with libpq
+      # If the connection does not work, try with psql
+      eval_command "pg_restore --clean -d ${TARGET_DB_NAME} ${DUMP_FILE_TO_RESTORE}"
+      ;;
+    *)
+      echo::err "The format $DUMP_FORMAT is not yet implemented"
+  esac
   echo::info "Restoration done"
 
   echo::info "Bye"
@@ -444,19 +461,17 @@ function backup_create_command(){
   
   
   # For the format documentation see: https://www.postgresql.org/docs/current/app-pgdump.html
-  local DUMP_FILE;
-  DUMP_FILE=$(get_db_dump_file "$DUMP_FORMAT" "$TARGET_DB_NAME")
+  local DUMP_PATH;
+  DUMP_PATH=$(get_db_dump_path "$DUMP_FORMAT" "$TARGET_DB_NAME")
   case "$DUMP_FORMAT" in
       "$DUMP_PLAIN_FORMAT")
-        EVAL_COMMAND="pg_dump --format=p ${CTL_DATABASE_NAME} | gzip  > ${DUMP_FILE}"
+        EVAL_COMMAND="pg_dump --format=p ${CTL_DATABASE_NAME} | gzip  > ${DUMP_PATH}"
         ;;
       "$DUMP_CUSTOM_FORMAT")
-        EVAL_COMMAND="pg_dump --format=c ${CTL_DATABASE_NAME} --file=${DUMP_FILE}"
+        EVAL_COMMAND="pg_dump --format=c ${CTL_DATABASE_NAME} --file=${DUMP_PATH}"
         ;;
       "$DUMP_FORMAT_DIR")
-        # F means FORMAT and d specify the directory FORMAT
-        # https://www.postgresql.org/docs/current/app-pgdump.html
-        EVAL_COMMAND="pg_dump --FORMAT=d ${CTL_DATABASE_NAME} -f ${DB_DUMP_ARCHIVE_DIR}"
+        EVAL_COMMAND="pg_dump --format=d ${CTL_DATABASE_NAME} --file ${DUMP_PATH}"
         ;;
        *)
          backup_create_help
@@ -473,7 +488,7 @@ function backup_create_command(){
   echo::info "Done"
 
   echo::info "Checking the dump file validity"
-  validate_postgres_dump "${DUMP_FILE}"
+  validate_postgres_dump "${DUMP_PATH}"
 
   echo::info "Creating a snapshot"
   eval_command "restic backup ${DUMP_SNAPSHOT_DIR}"
@@ -484,9 +499,18 @@ function backup_create_command(){
 }
 
 
+# @description list the backup dump dump snapshot
+# @arg $1 the snapshot id
+function backup_ls_command(){
 
-function backupLsCommand(){
-  restic find --long  "${PG_DUMP_DATA}"
+  SNAPSHOT_ID=${1:-}
+  if [ "$SNAPSHOT_ID" == "" ]; then
+    restic find --long  "${PG_DUMP_DATA}"
+  else
+    restic ls "$SNAPSHOT_ID"
+  fi
+
+
 }
 
 function dumpFetch(){
@@ -604,7 +628,7 @@ function backupCommand(){
       dumpFetch
       ;;
     ls)
-      backupLsCommand
+      backup_ls_command "${ARGS[@]}"
       ;;
     prune)
       backupPruneCommand
@@ -671,7 +695,7 @@ DUMP_PLAIN_FORMAT="plain"
 DUMP_PLAIN_FILE_EXTENSION="sql"
 DUMP_CUSTOM_FORMAT=custom
 DUMP_CUSTOM_FILE_EXTENSION="dump"
-DUMP_FORMAT_TAR="tar"
+# DUMP_FORMAT_TAR="tar"
 DUMP_FORMAT_DIR="dir"
 
 # The snapshot directory is the directory that restic snapshots.
@@ -681,7 +705,9 @@ DUMP_SNAPSHOT_DIR="$PG_DUMP_DATA/snapshot"
 mkdir -p "$DUMP_SNAPSHOT_DIR"
 
 # RESTORE_DIR_BASE where the files restored are going
-RESTORE_DIR_BASE=/tmp
+# We use a specific directory be able to mount a volume
+RESTORE_DIR_BASE=/tmp/snapshot-restore
+mkdir -p "$RESTORE_DIR_BASE"
 
 
 CLI_NAME=$(basename "$0") # Name of the cli
